<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>promise</title>
</head>
<body>
  
  <script src="../../vue.js"></script>
  <script>
    // setTimeout( () => console.log('hello world'), 1000)     // 用setTimeout模仿异步网络请求(setTimeout本身就是经过一定的延时之后触发回调函数)

    /*setTimeout( () => {         //回调地狱
      console.log("1");
      console.log("1");
      console.log("1");
      console.log("1");

      setTimeout( () => {
        console.log("2");
        console.log("2");
        console.log("2");
        console.log("2");

        setTimeout( () => {
          console.log("3");
          console.log("3");
          console.log("3");
          console.log("3");
        }, 1000)

      }, 1000)

    }, 1000)*/

    // new Promise( (resolve, reject) => {
    //   setTimeout( () => {
    //     resolve(( a, b ) => a+b)      // resolve函数可以传入参数，这个参数会被then接收
    //   } , 1000)
    // }).then( (add) => {
    //   console.log(add(1,2));
      

    //   return new Promise( ( resolve, reject) => {
    //     setTimeout( () => {
    //       resolve()
    //     }, 1000)
    //   }).then( () => {
    //     console.log("2");
    //     console.log("2");
    //     console.log("2");
    //     console.log("2");

    //     return new Promise( (resolve, reject ) => {
    //       setTimeout( () => {
    //         // resolve()
    //         reject("error!!")
    //       }, 1000) 
    //     }).then( () => {
    //         console.log("3");
    //         console.log("3");
    //         console.log("3");
    //         console.log("3");
    //     }, err => {
    //       console.log(err);
    //     })
    //   })

    // })
    

    // new Promise((resolve, reject) => {
    //   setTimeout( ()=> {
    //     resolve("aaa")
    //   }, 1000)
    // }).then( (response) => {
    //   console.log(response,"one");

    //   return Promise.resolve(response+"111")//如果new Promise只是为了使用他参数中的resolve函数去触发then，达到代码分离，那么可以直接用Promise.resolve
    // }).then( (response) => {                // reject也是同理，可以直接用 return Promise.reject("error message")，下面直接用catch即可
    //   console.log(response,"two");

    //   return Promise.resolve(response+"222")
    // }).then( (response) => {
    //   console.log(response,"three");
    // })

    // new Promise( (resolve, reject) => {

    //   setTimeout( () => {
    //     resolve("aaa")
    //   }, 1000)

    // }).then( (response) => {
    //   console.log(response, "one");

    //   return response + "111"       //甚至连Promise.resolve都不用写，直接return，底层会自动封装成Promise，然后去调用resolve

    // }).then( (response) => {
    //   console.log(response, "two");

    //   throw "error message"         //如果想调用resolve方法可以直接用return，如果想调用reject方法可以用throw抛出异常，配合catch使用
    // }).then( (response) => {
    //   console.log(response, "three");

    // }).catch( err => {
    //   console.log(err);
    // })
    
    

    const shareObj = {
      name: "hsj",
      age: 18
    }

    Vue.prototype.shareObj = shareObj

    Promise.all([                               // Promise.all方法，参数是数组，数组里面是一个一个的Promise，里面封装了异步请求
      new Promise( (resolve, reject) => {       // all方法可以等待所有异步请求结束之后在进行统一的结果处理，适用于，某一件事需要两个以上的请求完成时才能继续进行的时候
        setTimeout( () => {
          resolve("hello")
        }, 1000)
      }),
      new Promise( (resolve, reject) => {
        setTimeout( () => {
          resolve("world")
        }, 1000)
      })
    ]).then( (datas) => {                        // then中
      console.log(datas[0]);
      console.log(datas[1]);
    })
  </script>
</body>
</html>